apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgA8xgK5WFvx5qGO0LuOiAH286KFYfA7q44Zd1jXTrW/BFMAxxF4fcQXzpXKJkmQ9CHdoLuF5QZWL4KGgK8Rkg1LOpb9MKg7J19qf6IWYTFre49ydLFGLwOANsuHsZTKKMvf07O9AcCaQ2rvhGSWRUMmuaI0l0InTm+/OCSqM3FbmvA5H9fTCqZD6J8wQOq995SmxuNe+eQZh9JF55iJn8bchBvp5BOU5QXmjtfPWzcaoqhjm8/I9678nt0ocRZWRMkA8dsITZkWgjFNSLNXbF78QcK0/oAudsAV7+8Z8bI/YVoTfQKnc5MhHbKL4XghowhEkCrwTAIbVmgY5cAmibeRGxWZUmOoCNGKf7czcwYYYWFnICtCn1FbaOXNMes8ryKOcEZegejVY247fgLLIRo8nADV5zmdOxFIhPTTEjoM3venWD5r1CmKITND6USNOVsfy0wtscrKpRbC7DuKs+4mm3QkjFgTBUG0hMlRCh3RbXDULohAlP9ufrZ0A8drWQ6lbfCoU4z848HDvNkF7oy6PttZxQrh4xT2B+b4FyUC7XtTtnZ60ME0mj5yCEkG3+S/001qcZGiQV5UOfdiMpEjZD82RZh+ZM5O+XhAKnu/3eUldaD5W/0Wt6w1wkK+LGst1C75srRnsmjUsNxDaww3U6Pxo826FNKUYT4qkGC/x1r9Quvxu0RJgleqpJzLvW+aICL82ug41Du/hS4FCq3pX8g0Lq/zvbJpDsIdZl67jtLsbxoNjA==
    ARTIFACTORY_PASSWORD: AgCmbVRAkIYJT/XIfkYKSg0cHWVlQVQKm3TxNM2GUyA1OHibKqJagghz3Dwxwa5xe8X8jPn5n5QJ3SEmp/SVaCijTz0V/GYnEY/KlS3xhTsJiRnWlrCuRzbJUd8Y8Mwleabl2dYPFdp1Gn7BNassMJK/ddzcQ6R/6yf+PyUENdmHhqyjKcs/FfAecW/osoF5G+0p2kr0Y3fuGY9jbAMDxmz3aHHtAPYEPy1CBEgzP6WMkAbJ53K70dEdyA5eWuSgAhdsOBc2i9lJHYA0R+GJ6kVAuVJdfrNIKBMTnTOpKY9HDyqzKq4HJgyUKEOZhmGt0WhcHG4DGVtZimqgvWER9iiqtmnU7tAiy98sL0IJJtRO3LlkCN1zGRT86il398aUgiCT922wMcEUKjsHh/QEqbY209hchedAhOD8fWia9IUxVTq3dS9GcRFCdRlwJPRne2YVk4UG4fXri2XEi8gsUvj7K6rbXyY8RPMZT35L7PbwuE9vJZXNhlPt7vdRQOnBYpLKIrXFOW1WY5kC083F1Jfra5NaDegFiEY3sV9CS608dqZsWzy4kysKeqzmH3Jrj98tRz4dWw5LgWUUkIrbGSDXTSu+6BW7kFtZp+qNnOecD5r4SqPcoCEauDVlhmleuiSnxrxFJofs4LHADiIWeVWl9lO63X3q/XAKukIlSBEXwz2GAU5nkgEXpaCHZj4JRJ6oebtZAQ+et+igSBwOL5ZP4zDrhQ==
    ARTIFACTORY_URL: AgBV6mjnSNIn4ckeVf7FXC+hJB5p2OoRoA1RnI6UJof4+T/DxcD+CHiK4M1XntmOCIbIqEIiLysXtXlbTip1o33ZOzNZkr/YRW9KK5sc3FIfFr/sDeBXhyaUCEnb8FW7BadXjkvSOWwW/uiSa7MjBSEiXvNsNZjMkR/pVAlRY2YgN1c7hgQhPQZY+OYwwl5e62H9ebKcgVLiJLdk5a9Sg6qjP2Xzl/FAsVy5m2gi5ApmKNgk13S4DIddK6eX2zikZUIdlA7PZY8zCjj9VClvE4nj5ON/QH9MSwQVpDrqJwnRJZuVOW0y4/WOBhkxFLo0D1sW90W55SgMwQ6yzvJxeW5srsJ8512xt1xy/8QbVx56DNtrxeTzGOMzAv+wUVXzV3GiGBZiYuA3VFEKgsCDGJfCeSDPGYyutracvQlsxucTG+oaeyCA/P+ZX5r5DgTSfv5JzVTy5v2gBcawVjBat7C1JfdpjnC7BFJ8TeQcKXLklY4IE8/cyj8UDbSF9Bc5gEufLFCzOVG+QkVYR4FJPTCyh+sgDxyTAgH3CpNzms8g+tSP8UIHq8w+g7bqa8Bjw4U1PWNzm00C0gGd/zrx6U1n8zX79zXWQoCx7uJJSPrOqWMapCAK0PKTwkyJVu1Y2hq2MCE9WRnQ5Il+EiHRppkTcKX5yF6fl9XqeFtGhfMx/RAg7Zq/0mNgEuBMog3k9RRggvv7VDO/0yzzdGdoElI++L95/aQceHqXMwRT1fIW5djjGWqU5HJVdg==
    ARTIFACTORY_USER: AgAyl8qjzTTYwJiemS4WAaAeHareoy2xp3D4lRcZT6TV5aT8orFIJaCIFgBK9ChvsKiKyy9gBUUUR972MjVTEVzEHtW3s456kNl+fG6/+5+QSLA3m2aV3vMUSPauB4+Ple8niJH9Y+bUJEAh39OhRnzufHrxE45EatSVEamsIa/GCwHr68fJn0QovNMnFtuR2MxeKk12gzu3ttgbvyLoIlaZxuHRIu7lKpfarvBIkGtV78Z9jZY/C1Q+Wheo5k55ZSnnTJPhFVKrqtnSYjcRF37NmJDLttDP1nk7KXt5VOiDiGt+B5Lr9sxlBKNEsYmlEER80TjsqjN15jWOXJBIAR3S39N6I9LipkMUvYCbQbM1YrJcB9iZm1Ht9D6rL9F8lzwAN84lejO6Y4glfYXbReIgrSVB1gay12KCO5UgGisTdTWCR/fplSGb7pYGhV4b24kXnlkxj/+03bpzG7Dv0JSoYPxav+o/5XuWQXC0Ybj6wZtDUN9VNfTow/DqQQNgxob64uW/X1S4mCv6i8/UVDOXLKRDzUaj15FXEThYoj3iUJX8K07uhuiC1l7SlFeO2/99+Tpoh8JeXV+SKD3Um2ybvb3scD284YQ0yYVlaPTGfVtlg3dO/+buq2ylmCTFR5NuDtDoep9mftwq+uSTNQ7eHZUk2MqsdgPztci/IuMLtEDbUUSWQd5KLQpxYgT7UnkYk4gO0w==
  template:
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-11-17T06:09:58Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-11-17T06:10:54Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

