apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAbFbCmWqanXRuLKtGoz4Ad9jSkwZz+PPzxvf4QREZXHMxfMLkz3q29nuQNxIHxSjFaq193AvQyZQsrUOMK/1cijTLnoZadmpF7rTA8PQJ9z9s0hE96jWLZ9j3yhMeHVk4+OnsX8O4DUjc67VcxSkJjZgDqNfvoDyWAPI9DmH7jhMj+BIGNROX3YBtgOIQ1mLwq73KMEbvr1fyaqPdBEPt64qMk4hiC/j/T4NtYfzb4YMFGxiER2w0tuNqKsmJlO2IMx5C00DboHdvL5CG+IpQYb57qE33pJbjc/UEDQQ1GZwyr5G3Ds3EkUgIysHNZr83HhOugXOyE6hFSRs500cL4/+4shtPyO2xgZK40R9P22HYcRoFCfJlNh35KCWbcwSs48VDi3gMmCbMcYQkFft2q3b7Om6X0NU5dLJkx1SwLwgfLcOD6IcBH6xtQtSJIrsSsiZqKpuLKacJ4cED002gO4mzhdjvUhfouKlTs/sFELrNYaxSma427jp77GcmG5fBtM8bt9VIUUZByXHh15OT2kAsi7ov2iZ0rjcUy/sIOy/8Gprrby8ZSpjkl5MBeMmhcjUWsoZAuXnIVB7sVDUFfmn3qA700esrPdaX1IA/xgmOx7d/cKMhhvWyWdBrH5bflxIghdf/z+BHTrK/9+SniEYzzw4fD1P0K7tcn/TZ74qZguCHeAp+6X4tMJMvxrrwCHsY/3HrE7r33um79PqjA77JtKhS+aowpY3ndKDeROAbcgYmQvHSb
    username: AgBPxK7jH0+qQtqvihi7XTCkrCpqGpoK+n0jUqBIIJNP3hStHShBVGyFxzkt66J+kCspSIEuhDKfE1nKBWS2rnTSflyMujtDUbIGtA3X2/fwe1kelv0vAZ5URQklzJdRDrh4Wz/AlITw9eCtYlYb0EyqE7ZVba1oxi65b97kfi/u9RAPoMTQv6hknLCCc94qloL7i6VPdMI6HmzyfY+Gs7kc/5p5aYYP7xeySZvWaZciCJpJMMwuerrTZQjT8yvn+P4ssN7+h/a4QtJZxk1U7GM7JjWwHlnF9RL84T2WAybR28ilFSLmA0W6OeJhKbyuwwkdIjyldDMUnTEF/uva8bjThfTse0kK97voNsyvcj14PM5GyFheD9PIEaV5/MgasPaL641EM8T3Oc7tI63B85+AtrPQ8QtrOqnevjY5DwOIu+JK5OITeAq/Kxy45TEADKgbA1eCsy8m1XSKOj1kiE9kL3eDx20MFDTI09KnLVmSVZsvvtXKXdrPEN/BK35p8/MtKn5t8bCQwTJekFFdzCwFqdngtrPV9ZUyGFZ7UwCl/mwfwg4c+vixWJ0J2Rtry+qL+5nXh7rjz4BEg/xg4u+B0YemgenuRaJm4kyAF0Yg+l9FG1jHQSBqr5Oi2Ng0zTE7s0d9a2hkkRKccSLLPWxUOVtA8lfvNdTxy/Xp/KCQwsVSEEzxuFN2oCScLGoJPYkXCCpJLgIN4WJa
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

